---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
  ##
  ## Base operator rules
  ##
  - apiGroups:
      - ""
    resources:
      - secrets
      - pods
      - pods/exec
      - pods/log
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - apps
    resources:
      - deployments
      - daemonsets
      - replicasets
      - statefulsets
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  ##
  ## Rules for ripsaw.cloudbulldozer.io.ripsaw.cloudbulldozer.io/v1alpha1, Kind: Benchmark
  ##
  - apiGroups:
      - ripsaw.cloudbulldozer.io.ripsaw.cloudbulldozer.io
    resources:
      - benchmarks
      - benchmarks/status
      - benchmarks/finalizers
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
# +kubebuilder:scaffold:rules
  - apiGroups:
    - ""
    resources:
    - pods
    - daemonsets
    - services
    - endpoints
    - persistentvolumeclaims
    - virtualmachineinstances
    - events
    - configmaps
    - secrets
    - pods/log
    verbs:
    - '*'
  - apiGroups:
    - ""
    resources:
    - namespaces
    verbs:
    - get
  - apiGroups:
    - apps
    resources:
    - deployments
    - daemonsets
    - replicasets
    - statefulsets
    - deployments/finalizers
    verbs:
    - '*'
  - apiGroups:
    - monitoring.coreos.com
    resources:
    - servicemonitors
    verbs:
    - get
    - create
  - apiGroups:
    - kubevirt.io
    resources:
    - virtualmachineinstances
    verbs:
    - '*'
  - apiGroups:
    - ripsaw.cloudbulldozer.io
    resources:
    - '*'
    verbs:
    - '*'
  - apiGroups:
    - batch
    - extensions
    resources:
    - jobs
    verbs:
    - get
    - list
    - watch
    - create
    - update
    - patch
    - delete
  - apiGroups:
    - policy
    resources:
    - podsecuritypolicies
    verbs:
    - use
    resourceNames:
    - privileged
  - apiGroups:
    - security.openshift.io
    resourceNames:
    - privileged
    resources:
    - securitycontextconstraints
    verbs:
    - use
  - apiGroups:
    - hyperfoil.io
    resources:
    - hyperfoils
    verbs:
    - '*'
